import Head from 'next/head'
import { useTheme } from '@/hooks/use-theme'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styles from '@/styles/pages/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useTheme({
    dark: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    light: {
      primary: '#FFFFFF',
      secondary: '#000000',
    }
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
